CREATE TABLE KHOAHOC (
    MAKH varchar(255) PRIMARY KEY,
    TENKH varchar(255),
    NGAYBD date,
    NGAYKT date,
    CONSTRAINT CHK_DATE CHECK (NGAYBD < NGAYKT)
);

-- drop table

CREATE TABLE CHUONGTRINH (
    MACT varchar(255) PRIMARY KEY,
    TENCT varchar(255)
);

CREATE TABLE LOAILOP (
    MALOAI varchar(255) PRIMARY KEY,
    MACT varchar(255),
    TENLOAI varchar(255),
    CONSTRAINT FK_LOAILOP FOREIGN KEY (MACT) REFERENCES CHUONGTRINH(MACT)
);

CREATE TABLE LOP (
    MALOP varchar(255) PRIMARY KEY,
    MALOAI varchar(255),
    TENLOP varchar(255),
    SISO smallint CHECK (SISO > 12),
    MAKH varchar(255),
    CONSTRAINT FK_LOP FOREIGN KEY (MALOAI) REFERENCES LOAILOP(MALOAI), FOREIGN KEY (MAKH) REFERENCES KHOAHOC(MAKH)
);

CREATE TABLE HOCVIEN (
    MAHV varchar(255) PRIMARY KEY,
    TENHV varchar(255),
    GIOITINH smallint,
    NGAYSINH date,
    SDT int,
    DIACHI varchar(255)
);

CREATE TABLE PHIEUTHU (
    SOPT varchar(255) PRIMARY KEY,
    MAHV varchar(255),
    MALOP varchar(255),
    NGAYLAPPHIEU date,
    THANHTIEN int,
    CONSTRAINT FK_PHIEUTHU FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV), FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);

CREATE TABLE MONHOC (
    MAMH varchar(255) PRIMARY KEY,
    TENMH varchar(255)
);

CREATE TABLE DIEM (
    MAMH varchar(255),
    MAHV varchar(255),
    MALOP varchar(255),
    DIEM int,
    PRIMARY KEY(MAMH, MAHV, MALOP),
    CONSTRAINT FK_DIEM FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH), FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV), FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);
